config/routes.rb
Episodelog::Application.routes.draw do

  get "users/show"

  devise_for :users do
    get 'login', :to => 'devise/sessions#new'
    get 'logout', :to => 'devise/sessions#destroy'
    get 'signup', :to => 'devise/registrations#new'
  end

  resources :shows do
    resources :episodes
    get 'episodes/:season/:episode' => 'episodes#show'
  end

  resources :users
  resources :friends
  resources :friendships

  match 'dashboard' => 'home#dashboard'

  match 'update_show_state' => 'application#update_show_state'
  match 'update_episode_state' => 'application#update_episode_state'
  match 'update_season_state' => 'application#update_season_state'

  root :to => 'home#index'

end

app/views/shared/_episode.html.erb
      <tr>
        <td><%= check_box_tag 'episodes[]', value = episode.id, checked = episode.watched?(current_user), :dataurl => ajax_watched_episode_path(episode) %></td>
        <td><%= episode.episode_number %></td>
        <td><%= episode.season %></td>
        <td><%= link_to episode.name, episode_path(episode) %></td>
        <td><%= episode.air_date.strftime('%m/%d/%Y') %></td>
      </tr>

app/views/shared/_episode.mobile.erb
<div id="episode_<%= episode.id %>" class="episode<%= (current_user.episodes.include?(episode) ? ' watched' : '') if current_user %>">
  <div class="status">
    <%= current_user.episodes.include?(episode) ? link_to('watched', '', :class => 'remove') : link_to('-', '', :class => 'add') if current_user %>
  </div>

  <% link_to show_episode_path(@show.short_name, episode.id), :class => 'details' do %>
    <h3 class="episode_number"><%= episode.name %></h3>
    <p>Episode <%= episode.episode %></p>
  <% end %>
</div>

app/views/shared/_ga.erb
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-251833-16']);
  _gaq.push(['_setDomainName', '.episodelog.tv']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>

app/views/shared/_gs.html.erb
<script type="text/javascript" charset="utf-8">
  var is_ssl = ("https:" == document.location.protocol);
  var asset_host = is_ssl ? "https://s3.amazonaws.com/getsatisfaction.com/" : "http://s3.amazonaws.com/getsatisfaction.com/";
  document.write(unescape("%3Cscript src='" + asset_host + "javascripts/feedback-v2.js' type='text/javascript'%3E%3C/script%3E"));
</script>

<script type="text/javascript" charset="utf-8">
  var feedback_widget_options = {};

  feedback_widget_options.display = "overlay";  
  feedback_widget_options.company = "episodelog";
  feedback_widget_options.placement = "left";
  feedback_widget_options.color = "#404040";
  feedback_widget_options.style = "problem";

  var feedback_widget = new GSFN.feedback_widget(feedback_widget_options);
</script>

app/views/shared/_login.html.erb
<%- form_tag new_user_session_path do -%>
  <%= text_field_tag 'user[email]', nil, :placeholder => 'Email', :size => 20 %>
  <%= password_field_tag 'user[password]', nil, :placeholder => 'Password', :size => 20 %>
  <%= submit_tag 'Log in', :class => 'button' %>
  <%= link_to 'sign up', new_user_registration_path %><br />
<%- end -%>

app/views/shared/_panel.html.erb
    <%- if user_signed_in? -%>
      <div id="panel" class="user-details">
        <%= image_tag("http://www.gravatar.com/avatar.php?gravatar_id=#{Digest::MD5::hexdigest(current_user.email)}", :alt => 'Avatar', :class => 'avatar') %>
        <div id="controls">
          <%= current_user.email %><br />
          <%= link_to "preferences", edit_user_registration_path %> |
          <%= link_to 'logout', logout_path %>
        </div>
      </div>
    <%- else -%>
      <div id="panel" class="login">
<%= render :partial => 'shared/login' %>
      </div>
    <%- end -%>

app/views/shared/_progress_bar.html.erb
<% season ||= nil %>
<div class="progress">
  <div class="complete" style="width: <%= progress(show, (season ? season : nil)) %>px;"></div>
  <span class="copy"><%= progress(show, (season ? season : nil)) == 100 ? "completed" : "#{progress(show, (season ? season : nil))}% complete" %></span>
</div>

app/views/shared/_show.html.erb
<div id="show_<%= show.id %>" class="show<%= (current_user.shows.include?(show) ? ' favorite' : '') if current_user %>">
  <div class="details">
    <h3><%= link_to show.name, show_path(show), :class => 'test' %></h3>
    <p><%= link_to 'episodes', show_episodes_path(show) %><%=raw ' | ' + (current_user.shows.include?(show) ? link_to('remove', '', :class => 'remove') : link_to('favorite', '', :class => 'add')) if current_user %></p>
    <div class="show-details">
      <p><%= pluralize show.seasons.size, "season" %>, <%= pluralize show.episodes.size, "episode" %></p>
    </div>
  </div>
</div>

app/views/shared/_show.mobile.erb
<div id="show_<%= show.id %>" class="show<%= (current_user.shows.include?(show) ? ' favorite' : '') if current_user %>">
  <div class="status">
    <%= current_user.shows.include?(show) ? link_to('remove', '', :class => 'remove') : link_to('favorite', '', :class => 'add') if current_user %>
  </div>

  <% link_to show_episodes_path(show), :class => 'details' do %>
    <h3><%= show.name %></h3>
    <p><%= pluralize show.seasons.size, 'season' %>, <%= pluralize(show.episodes.size, 'episode') %></p>
  <% end %>
</div>

app/views/shared/_storeitem.html.erb
<div class="storeitem">
  <p><%= link_to image_tag('store/tng-first-season.png'), get_store_url('astore','B00005Y1NF') %></p>
  <p><%= link_to 'Star Trek TNG - First Season', get_store_url('astore','B00005Y1NF') %></p>
</div>