config/routes.rb
Episodelog::Application.routes.draw do

  get "users/show"

  devise_for :users do
    get 'login', :to => 'devise/sessions#new'
    get 'logout', :to => 'devise/sessions#destroy'
    get 'signup', :to => 'devise/registrations#new'
  end

  resources :shows do
    resources :episodes
    get 'episodes/:season/:episode' => 'episodes#show'
  end

  resources :users
  resources :friends
  resources :friendships

  match 'dashboard' => 'home#dashboard'

  match 'update_show_state' => 'application#update_show_state'
  match 'update_episode_state' => 'application#update_episode_state'
  match 'update_season_state' => 'application#update_season_state'

  root :to => 'home#index'

end

app/models/episode.rb
class Episode < ActiveRecord::Base
  has_many :watched_episodes
  has_many :users, :through => :watched_episodes

  belongs_to :show

  # scope :by_show, lambda { |show| where(:show_id => show.id).sort_by { |s| self.season } }

  def watched?(user)
    user.episodes.include?(self)
  end
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  before_filter :authenticate_user!

  def index
    if params[:show_id]
      @show = Show.find_by_short_name(params[:show_id])
      @episodes = Episode.where(:show_id => @show.id).order('season asc').order('episode asc').order('air_date asc').group_by(&:season)
    end
  end

  def show    
    if params[:show_id]
      @show = Show.find_by_short_name(params[:show_id])
      @episode = Episode.where(:show_id => @show.id, :id => params[:id]).first
    else
      @episode = Episode.find(params[:id])
    end
  end

  def new
    @episode = Episode.new
  end

  def edit
    @episode = Episode.find(params[:id])
  end

  def create
    @episode = Episode.new(params[:episode])

    respond_to do |format|
      if @episode.save
        format.html { redirect_to(@episode, :notice => 'Episode was successfully created.') }
      else
        format.html { render :action => "new" }
      end
    end
  end

  def update
    @episode = Episode.find(params[:id])

    respond_to do |format|
      if @episode.update_attributes(params[:episode])
        format.html { redirect_to(@episode, :notice => 'Episode was successfully updated.') }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  def destroy
    @episode = Episode.find(params[:id])
    @episode.destroy

    respond_to do |format|
      format.html { redirect_to(episodes_url) }
    end
  end
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/views/episodes/_form.html.erb
<%= form_for(@episode) do |f| %>
  <% if @episode.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@episode.errors.count, "error") %> prohibited this episode from being saved:</h2>

      <ul>
      <% @episode.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/episodes/edit.html.erb
<h1>Editing episode</h1>

<%= render 'form' %>

<%= link_to 'Show', @episode %> |
<%= link_to 'Back', episodes_path %>

app/views/episodes/index.html.erb
<p>&laquo; <%= link_to "Back to show details", show_path(@show.short_name) %></p>

<h1 id="show_<%= @show.id %>" class="show_name"><%= @show.name %></h1>

<% @episodes.each do |season, episodes| %>
<table id="season_<%= season %>_episodes" class="season_episodes">
  <tr id="season_<%= season %>" class="season">
    <td class="checkbox"><%= check_box_tag 'seasons[]', season, false, :id => "season_state_#{season}" %></td>
    <td class="season_number" colspan="3"><h3>Season <%= season %></h3></td>
  </tr>
  <% episodes.each do |episode| %>
  <tr id="episode_<%= episode.id %>" class="episode<%= episode.watched?(current_user) ? ' watched' : '' %>">
    <td class="checkbox"><%= check_box_tag 'episodes[]', episode.id, episode.watched?(current_user), :id => "episode_state_#{episode.id}", :style => 'display: none;' %></td>
    <td class="episode_number"><%= episode.episode %></td>
    <td class="name"><%= link_to episode.name, show_episode_path(@show.short_name, episode.id) %></td>
    <td class="air_date"><%= episode.air_date ? episode.air_date.strftime('%m/%d/%Y') : '' %></td>
  </tr>
  <% end %>
</table>
<% end %>

<p>&laquo; <%= link_to "Back to show details", show_path(@show.short_name) %></p>

app/views/episodes/index.mobile.erb
<% content_for :left_button do %>
  <% link_to('Dashboard', root_path, :class => 'back') %>
<% end %>

<% content_for :nav_title do %>
  <div id="title"><%= @show.name %></div>
<% end %>

<% content_for :right_button do %>
  <% link_to('', shows_path, :class => 'favorite_button') %>
<% end %>

<div id="show_progress" class="section">
  <h3>Progress</h3>
  <table>
    <tr class="season">
      <td><span class="season_number">Overall</span></td>
      <td>
        <%= render :partial => 'shared/progress_bar.html.erb', :locals => { :show => @show } %>
      </td>
    </tr>
    <% @show.seasons.each do |s| %>
    <tr class="season">
      <td><span class="season_number">Season <%= s %></span></td>
      <td>
        <%= render :partial => 'shared/progress_bar.html.erb', :locals => { :show => @show, :season => s } %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

<hr />

<div id="episodes" class="section">
  <% @episodes.each do |season, episodes| %>
  <div id="season_<%= season %>_episodes" class="season_episodes">
    <div id="season_<%= season %>" class="season">
      <h3>Season <%= season %></h3>
    </div>

    <%= render :partial => 'shared/episode', :collection => episodes %>
  </div>
  <% end %>
</div>

app/views/episodes/new.html.erb
<h1>New episode</h1>

<%= render 'form' %>

<%= link_to 'Back', episodes_path %>

app/views/episodes/show.html.erb
<p>&laquo; <%= link_to "Back to #{@show.name} episodes", show_episodes_path(@show.short_name) %></p>

<p id="notice"><%= notice %></p>

<h2><%= @episode.name %></h2>
<p>Season <%= @episode.season %>, Episode <%= @episode.episode %></p>
<%= content_tag( :p, 'Air Date: ' + @episode.air_date.strftime('%m/%d/%Y') ) if @episode.air_date %>
<p><%= @episode.synopsis %></p>

app/views/episodes/show.mobile.erb
<% content_for :left_button do %>
  <% link_to('Dashboard', root_path, :class => 'back') %>
<% end %>

<% content_for :nav_title do %>
  <div id="title"><%= link_to @show.name, show_episodes_path(@show) %></div>
<% end %>

<% content_for :right_button do %>
  <% link_to('', shows_path, :class => 'search_button') %>
<% end %>

<div class="section">
  <h2><%= @episode.name %></h2>
  <p>Season <%= @episode.season %>, Episode <%= @episode.episode %></p>
  <%= content_tag( :p, 'Air Date: ' + @episode.air_date.strftime('%m/%d/%Y') ) if @episode.air_date %>
  <p><%= @episode.synopsis %></p>
</div>