config/routes.rb
Episodelog::Application.routes.draw do

  get "users/show"

  devise_for :users do
    get 'login', :to => 'devise/sessions#new'
    get 'logout', :to => 'devise/sessions#destroy'
    get 'signup', :to => 'devise/registrations#new'
  end

  resources :shows do
    resources :episodes
    get 'episodes/:season/:episode' => 'episodes#show'
  end

  resources :users
  resources :friends
  resources :friendships

  match 'dashboard' => 'home#dashboard'

  match 'update_show_state' => 'application#update_show_state'
  match 'update_episode_state' => 'application#update_episode_state'
  match 'update_season_state' => 'application#update_season_state'

  root :to => 'home#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EpisodeLog</title>
    <%= hoptoad_javascript_notifier %>
    <%= stylesheet_link_tag 'episodelog.css' %>
    <%= javascript_include_tag 'jquery-1.6.1.min', 'application' %>
    <%= javascript_include_tag 'ga.js' %>
    <%= csrf_meta_tag %>
    <%= render :partial => 'shared/gs' %>
    <%= render :partial => 'shared/ga' %>
  </head>
  <body>
    <div id="wrapper">
      <div id="header_container">
        <div id="header">
          <div id="logo">
            <h1>EpisodeLog</h1>
            <% controller.controller_name + ' - ' + controller.action_name %>
          </div>
          <%= render :partial => 'shared/panel' %>
        </div>
      </div>

      <div id="nav_container">
        <div id="nav">
          <ul>
            <%= content_tag( :li, link_to('Dashboard', root_path) ) if user_signed_in? %>
            <li><%= link_to 'Shows', shows_path %></li>
            <%# content_tag( :li, link_to('Friends', friends_path) ) if user_signed_in? %>
          </ul>
        </div>
      </div>

      <%= content_tag( :p, notice, :id => 'flash', :class => 'notice', :style => (notice ? '' : 'display: none') ) %>

      <div id="body">
        <div id="content">
          <%= yield %>
        </div>
      </div>
    </div>

    <div id="footer_container">
      <div id="footer">
        <p>
          <%= link_to 'Feedback', 'https://getsatisfaction.com/episodelog' %> <span class="divider">|</span>
          <%= link_to 'Suggest a Show', 'https://convore.com/episodelog/show-suggestions' %> <span class="divider">|</span>
          Copyright &copy; <%= Time.now.year %> <%= link_to 'Cylence, Inc.', 'http://cylence.com' %>
        </p>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.mobile.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EpisodeLog</title>
    <%= hoptoad_javascript_notifier %>
    <link rel="apple-touch-icon" href="icon.png" />
    <link rel="apple-touch-startup-image" href="startup.png" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0;"/>
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <%= stylesheet_link_tag 'mobile.css' %>
    <%= javascript_include_tag 'jquery-1.6.1.min', 'mobile' %>
    <%= javascript_include_tag 'ga.js' %>
    <%= csrf_meta_tag %>
    <%= render :partial => 'shared/ga' %>
  </head>
  <body>
    <nav>
      <% if content_for?(:left_button) %>
      <div id="left_button"><%= yield :left_button %></div>
      <% end %>

      <% if content_for?(:right_button) %>
      <div id="right_button"><%= yield :right_button %></div>
      <% end %>

      <h1><%= yield :nav_title %></h1>
    </nav>

    <%= content_tag( :p, notice, :id => 'flash', :class => 'notice section', :style => (notice ? '' : 'display: none') ) %>

    <div id="content">
      <%= yield %>
    </div>

    <%= content_tag :div, :id => 'footer' do %>
      <%= link_to 'Sign Out', logout_path %>
    <% end if current_user %>
  </body>
</html>